name: 🐛 Bug Report
description: Report a bug to help us improve the project
title: '[BUG] '
labels: ['bug', 'triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this bug! 🙏

        Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clearly describe the bug you encountered
      placeholder: 'When I tried to [action], [unexpected behavior] happened instead of [expected behavior]'
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide exact steps to reproduce the bug
      placeholder: |
        1. Go to [location]
        2. Click on [element]
        3. Enter [data]
        4. Observe [behavior]
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: 'The system should...'
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: 'Instead, the system...'
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How critical is this bug?
      options:
        - '🟢 Low (cosmetic issue, workaround available)'
        - '🟡 Medium (affects functionality, no easy workaround)'
        - '🔴 High (major functionality broken)'
        - '🔴🔴 Critical (system unusable or data loss)'
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide relevant system information
      placeholder: |
        - OS: [e.g., macOS 14.1, Windows 11, Ubuntu 23.10]
        - Browser: [e.g., Chrome 119, Firefox 121]
        - Node.js/Runtime: [version]
        - Project Version: [version]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs / Screenshots
      description: Include error messages, stack traces, or screenshots
      placeholder: 'Paste error output here or attach screenshots'

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context that might be helpful?
      placeholder: 'I noticed this started happening after version X...'

  - type: checkboxes
    id: verification
    attributes:
      label: Verification
      description: Please verify before submitting
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I can reproduce this bug consistently
          required: true
        - label: I have provided all relevant information
          required: true
